import csv
import json
import os
import sys
import tempfile
import unittest


ROOT = os.path.dirname(os.path.dirname(__file__))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

import make_paper_figures  # noqa: E402


class MakePaperFiguresTest(unittest.TestCase):
    def test_read_results_prefers_summary_csv(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            results_path = os.path.join(tmpdir, "cartpole_results.csv")
            summary_path = os.path.join(tmpdir, "cartpole_summary.csv")
            with open(results_path, "w", newline="", encoding="utf-8") as handle:
                writer = csv.DictWriter(handle, fieldnames=["policy", "train_success", "test_success", "test_reward"])
                writer.writeheader()
                writer.writerow(
                    {
                        "policy": "raw",
                        "train_success": "0.0",
                        "test_success": "0.0",
                        "test_reward": "1.0",
                    }
                )
            with open(summary_path, "w", newline="", encoding="utf-8") as handle:
                writer = csv.DictWriter(
                    handle,
                    fieldnames=["policy", "train_success_mean", "test_success_mean", "test_reward_mean"],
                )
                writer.writeheader()
                writer.writerow(
                    {
                        "policy": "summary",
                        "train_success_mean": "1.0",
                        "test_success_mean": "0.5",
                        "test_reward_mean": "10.0",
                    }
                )

            original_results = make_paper_figures.RESULTS_CSV
            original_summary = make_paper_figures.SUMMARY_CSV
            try:
                make_paper_figures.RESULTS_CSV = results_path
                make_paper_figures.SUMMARY_CSV = summary_path
                rows = make_paper_figures.read_results()
            finally:
                make_paper_figures.RESULTS_CSV = original_results
                make_paper_figures.SUMMARY_CSV = original_summary

        self.assertEqual(rows[0]["policy"], "summary")
        self.assertEqual(make_paper_figures.metric(rows[0], "test_reward"), 10.0)

    def test_read_results_falls_back_to_raw_csv(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            results_path = os.path.join(tmpdir, "cartpole_results.csv")
            summary_path = os.path.join(tmpdir, "missing_summary.csv")
            with open(results_path, "w", newline="", encoding="utf-8") as handle:
                writer = csv.DictWriter(handle, fieldnames=["policy", "train_success", "test_success", "test_reward"])
                writer.writeheader()
                writer.writerow(
                    {
                        "policy": "raw",
                        "train_success": "0.25",
                        "test_success": "0.0",
                        "test_reward": "2.0",
                    }
                )

            original_results = make_paper_figures.RESULTS_CSV
            original_summary = make_paper_figures.SUMMARY_CSV
            try:
                make_paper_figures.RESULTS_CSV = results_path
                make_paper_figures.SUMMARY_CSV = summary_path
                rows = make_paper_figures.read_results()
            finally:
                make_paper_figures.RESULTS_CSV = original_results
                make_paper_figures.SUMMARY_CSV = original_summary

        self.assertEqual(rows[0]["policy"], "raw")
        self.assertEqual(make_paper_figures.metric(rows[0], "train_success"), 0.25)

    def test_write_results_table_uses_summary_metrics(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            table_path = os.path.join(tmpdir, "table.tex")
            make_paper_figures.write_results_table(
                [
                    {
                        "policy": "Programmatic state machine",
                        "train_success_mean": "1.0",
                        "test_success_mean": "0.2",
                        "train_reward_mean": "250.0",
                        "test_reward_mean": "6275.4",
                    }
                ],
                table_path,
            )
            with open(table_path, encoding="utf-8") as handle:
                table = handle.read()

        self.assertIn("Generated by scripts/make_paper_figures.py", table)
        self.assertIn("Programmatic PSM & 1.00 & 0.20 & 250.0 & 6275.4", table)
        self.assertIn("\\bottomrule", table)

    def test_read_ppo_metric_files_skips_empty_history(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            good_path = os.path.join(tmpdir, "good_metrics.json")
            empty_path = os.path.join(tmpdir, "empty_metrics.json")
            with open(good_path, "w", encoding="utf-8") as handle:
                json.dump(
                    {
                        "config": {"policy_type": "mlp", "seed": 0},
                        "eval_history": [
                            {
                                "timesteps": 32,
                                "train_success_rate": 0.5,
                                "test_success_rate": 0.25,
                            }
                        ],
                    },
                    handle,
                )
            with open(empty_path, "w", encoding="utf-8") as handle:
                json.dump({"config": {"policy_type": "mlp"}, "eval_history": []}, handle)

            metric_files = make_paper_figures.read_ppo_metric_files([os.path.join(tmpdir, "*_metrics.json")])

        self.assertEqual(len(metric_files), 1)
        self.assertEqual(make_paper_figures.metric_label(metric_files[0]), "MLP seed 0")

    def test_plot_ppo_training_curves_writes_png(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            outpath = os.path.join(tmpdir, "curve.png")
            wrote = make_paper_figures.plot_ppo_training_curves(
                [
                    {
                        "path": "synthetic.json",
                        "payload": {
                            "config": {"policy_type": "mlp", "seed": 0},
                            "eval_history": [
                                {
                                    "timesteps": 32,
                                    "train_success_rate": 0.5,
                                    "test_success_rate": 0.25,
                                },
                                {
                                    "timesteps": 64,
                                    "train_success_rate": 1.0,
                                    "test_success_rate": 0.5,
                                },
                            ],
                        },
                    }
                ],
                outpath,
            )

            self.assertTrue(wrote)
            self.assertTrue(os.path.exists(outpath))
            self.assertGreater(os.path.getsize(outpath), 0)


if __name__ == "__main__":
    unittest.main()
