from __future__ import annotations

import csv
import glob
import json
import os

import matplotlib.pyplot as plt
import numpy as np


ROOT = os.path.dirname(os.path.dirname(__file__))
RESULTS_CSV = os.path.join(ROOT, "artifacts", "results", "cartpole_results.csv")
SUMMARY_CSV = os.path.join(ROOT, "artifacts", "results", "cartpole_summary.csv")
OUT_DIR = os.path.join(ROOT, "essay", "figures")
TABLE_TEX = os.path.join(ROOT, "essay", "cartpole_results_table.tex")
PPO_METRICS_GLOBS = [
    os.path.join(ROOT, "artifacts", "cartpole_ppo_*_metrics.json"),
    os.path.join(ROOT, "artifacts", "ppo_sweep", "metrics", "*.json"),
]


def read_results() -> list[dict[str, str]]:
    path = SUMMARY_CSV if os.path.exists(SUMMARY_CSV) else RESULTS_CSV
    with open(path, newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def metric(row: dict[str, str], name: str) -> float:
    return float(row.get(f"{name}_mean") or row[name])


def display_policy(name: str) -> str:
    return name.replace("Programmatic state machine", "Programmatic PSM").replace("PPO-LSTM", "PPO-LSTM")


def write_results_table(rows: list[dict[str, str]], outpath: str = TABLE_TEX) -> None:
    lines = [
        "% Generated by scripts/make_paper_figures.py from CartPole result artifacts.",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Policy & Train succ. & Test succ. & Train rew. & Test rew. \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(
            f"{display_policy(row['policy'])} & "
            f"{metric(row, 'train_success'):.2f} & "
            f"{metric(row, 'test_success'):.2f} & "
            f"{metric(row, 'train_reward'):.1f} & "
            f"{metric(row, 'test_reward'):.1f} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    with open(outpath, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def plot_success_bars(rows: list[dict[str, str]]) -> None:
    labels = [row["policy"].replace("Programmatic state machine", "Programmatic PSM") for row in rows]
    train = [metric(row, "train_success") for row in rows]
    test = [metric(row, "test_success") for row in rows]
    x = np.arange(len(labels))
    width = 0.36

    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    ax.bar(x - width / 2, train, width, label="Train: 5s, len=0.5", color="#3b6ea8")
    ax.bar(x + width / 2, test, width, label="Test: 300s, len=1.0", color="#b84a4a")
    ax.set_ylim(0.0, 1.05)
    ax.set_ylabel("Success rate")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=12, ha="right")
    ax.grid(axis="y", alpha=0.25)
    ax.legend(frameon=False, loc="upper right")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "cartpole_success_rates.png"), dpi=220)
    plt.close(fig)


def plot_survival_rewards(rows: list[dict[str, str]]) -> None:
    labels = [row["policy"].replace("Programmatic state machine", "Programmatic PSM") for row in rows]
    rewards = [metric(row, "test_reward") for row in rows]
    colors = ["#6f8fb8", "#8aa777", "#c58b47"]

    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    ax.bar(np.arange(len(labels)), rewards, color=colors)
    ax.axhline(15_000, color="black", linewidth=1.0, linestyle="--", alpha=0.6)
    ax.text(2.2, 14_650, "full 300s horizon", ha="right", va="top", fontsize=8)
    ax.set_ylabel("Mean test survival reward")
    ax.set_xticks(np.arange(len(labels)))
    ax.set_xticklabels(labels, rotation=12, ha="right")
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "cartpole_test_survival_reward.png"), dpi=220)
    plt.close(fig)


def plot_switch_boundary() -> None:
    theta = np.linspace(-0.22, 0.22, 200)
    omega = -10.0 * theta

    fig, ax = plt.subplots(figsize=(5.2, 3.6))
    ax.plot(theta, omega, color="#2f2f2f", linewidth=2.0)
    ax.fill_between(theta, omega, 2.5, color="#3b6ea8", alpha=0.15, label="push right")
    ax.fill_between(theta, -2.5, omega, color="#b84a4a", alpha=0.15, label="push left")
    ax.set_xlim(-0.22, 0.22)
    ax.set_ylim(-2.5, 2.5)
    ax.set_xlabel(r"pole angle $\theta$")
    ax.set_ylabel(r"angular velocity $\dot{\theta}$")
    ax.set_title(r"Programmatic switch: $5\theta + 0.5\dot{\theta}=0$")
    ax.grid(alpha=0.25)
    ax.legend(frameon=False, loc="upper right")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "programmatic_switch_boundary.png"), dpi=220)
    plt.close(fig)


def read_ppo_metric_files(patterns: list[str] | None = None) -> list[dict[str, object]]:
    metric_files: list[dict[str, object]] = []
    for pattern in patterns or PPO_METRICS_GLOBS:
        for path in sorted(glob.glob(pattern)):
            with open(path, encoding="utf-8") as handle:
                payload = json.load(handle)
            history = payload.get("eval_history", [])
            if history:
                metric_files.append({"path": path, "payload": payload})
    return metric_files


def metric_label(metric_file: dict[str, object]) -> str:
    payload = metric_file["payload"]
    config = payload.get("config", {})
    policy = str(config.get("policy_type", "ppo")).upper()
    seed = config.get("seed")
    return f"{policy} seed {seed}" if seed is not None else policy


def plot_ppo_training_curves(metric_files: list[dict[str, object]], outpath: str | None = None) -> bool:
    if not metric_files:
        return False
    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    for metric_file in metric_files:
        payload = metric_file["payload"]
        history = payload["eval_history"]
        timesteps = [entry["timesteps"] for entry in history]
        train_success = [entry["train_success_rate"] for entry in history]
        test_success = [entry["test_success_rate"] for entry in history]
        label = metric_label(metric_file)
        ax.plot(timesteps, train_success, linewidth=1.8, label=f"{label} train")
        ax.plot(timesteps, test_success, linewidth=1.4, linestyle="--", label=f"{label} test")
    ax.set_ylim(-0.02, 1.02)
    ax.set_xlabel("Environment timesteps")
    ax.set_ylabel("Success rate")
    ax.grid(alpha=0.25)
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(outpath or os.path.join(OUT_DIR, "cartpole_ppo_training_curves.png"), dpi=220)
    plt.close(fig)
    return True


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    rows = read_results()
    write_results_table(rows)
    plot_success_bars(rows)
    plot_survival_rewards(rows)
    plot_switch_boundary()
    plot_ppo_training_curves(read_ppo_metric_files())


if __name__ == "__main__":
    main()
